In [3]:
import os

print(os.getcwd())

c:\Users\navya\OneDrive\Desktop\Care flow AI\notebooks

In [4]:
import os

print(os.listdir("../datasets/hospital_patient"))

['Hospital Patient .csv']

In [5]:
import pandas as pd
import numpy as np

In [ ]:
patients = pd.read_csv("../datasets/hospital_patient/Hospital Patient .csv")

appointments = pd.read_csv("../datasets/appointments/appointments.csv")

er = pd.read_csv("../datasets/hospital_er/Hospital ER_Data.csv")

patient_flow = pd.read_csv("../datasets/patient_flow/healthcare_analytics_patient_flow_data.csv")

doctors = pd.read_csv("../datasets/doctors/doctors.csv")

departments = pd.read_csv("../datasets/departments/departments.csv")

In [ ]:

patient_flow = pd.read_csv("../datasets/patient_flow/healthcare_analytics_patient_flow_data.csv")

doctors = pd.read_csv("../datasets/doctors/doctors.csv")

departments = pd.read_csv("../datasets/departments/departments.csv")

In [11]:
print("Patients Dataset :", patients.shape)
print("Appointments Dataset :", appointments.shape)
print("Hospital ER Dataset :", er.shape)
print("Patient Flow Dataset :", patient_flow.shape)
print("Doctors Dataset :", doctors.shape)
print("Departments Dataset :", departments.shape)

Patients Dataset : (984, 15)
Appointments Dataset : (200, 7)
Hospital ER Dataset : (9216, 12)
Patient Flow Dataset : (9216, 11)
Doctors Dataset : (10, 7)
Departments Dataset : (10, 2)

In [12]:
print("Patients")
display(patients.head())

print("Appointments")
display(appointments.head())

print("Hospital ER")
display(er.head())

print("Patient Flow")
display(patient_flow.head())

print("Doctors")
display(doctors.head())

print("Departments")
display(departments.head())

Patients

,Patient_ID,Age,Gender,Condition,Medication,Admission_Date,Discharge_Date,Patient_State,Year_of_Admission,Length_of_Stay,Readmission,Outcome,Satisfaction,Insurance_Claimed,Total_Cost
0,1,45,Female,Heart Disease,Angioplasty,07-02-2024,12-02-2024,Kerala,2024,5,No,Recovered,4,Yes,15000
1,2,60,Male,Diabetes,Insulin Therapy,11-03-2023,14-03-2023,Goa,2023,3,Yes,Stable,3,No,2000
2,3,32,Female,Fractured Arm,X-Ray and Splint,02-01-2025,03-01-2025,Maharastra,2025,1,No,Recovered,5,Yes,500
3,4,75,Male,Stroke,CT Scan and Medication,30-12-2023,06-01-2024,Manipur,2023,7,Yes,Stable,2,No,10000
4,5,50,Female,Cancer,Surgery and Chemotherapy,10-05-2022,20-05-2022,Mizoram,2022,10,No,Recovered,4,No,25000

Appointments

,appointment_id,patient_id,doctor_id,appointment_date,appointment_time,reason_for_visit,status
0,A001,P034,D009,2023-08-09,15:15:00,Therapy,Scheduled
1,A002,P032,D004,2023-06-09,14:30:00,Therapy,No-show
2,A003,P048,D004,2023-06-28,8:00:00,Consultation,Cancelled
3,A004,P025,D006,2023-09-01,9:15:00,Consultation,Cancelled
4,A005,P040,D003,2023-07-06,12:45:00,Emergency,No-show

Hospital ER

,Patient Id,Patient Admission Date,Patient First Inital,Patient Last Name,Patient Gender,Patient Age,Patient Race,Department Referral,Patient Admission Flag,Patient Satisfaction Score,Patient Waittime,Patients CM
0,145-39-5406,20-03-2024 08:47,H,Glasspool,M,69,White,NaN,False,10.0,39,0
1,316-34-3057,15-06-2024 11:29,X,Methuen,M,4,Native American/Alaska Native,NaN,True,NaN,27,0
2,897-46-3852,20-06-2024 09:13,P,Schubuser,F,56,African American,General Practice,True,9.0,55,0
3,358-31-9711,04-02-2024 22:34,U,Titcombe,F,24,Native American/Alaska Native,General Practice,True,8.0,31,0
4,289-26-0537,04-09-2024 17:48,Y,Gionettitti,M,5,African American,Orthopedics,False,NaN,10,0

Patient Flow

,Patient Id,Patient Admission Date,Patient Admission Time,Merged,Patient Gender,Patient Age,Patient Race,Department Referral,Patient Admission Flag,Patient Satisfaction Score,Patient Waittime
0,780-96-6113,9/9/2024,9:25:00 AM,W. Breede,Female,63,African American,NaN,Not Admission,5.0,32
1,714-35-6722,9/9/2024,4:42:00 PM,Y. Baldetti,Male,31,Asian,Orthopedics,Not Admission,NaN,22
2,571-85-3714,9/9/2024,12:14:00 AM,M. Semerad,Male,75,White,General Practice,Not Admission,NaN,16
3,404-43-9499,9/9/2024,8:33:00 PM,K. Blaydes,Male,79,African American,General Practice,Admission,NaN,38
4,552-51-5855,9/9/2024,7:25:00 PM,F. Dickerson,Female,24,African American,NaN,Admission,NaN,36

Doctors

,doctor_id,doctor_name,department,specialization,experience_years,consultation_time_min,availability
0,D101,Dr. Rajesh Kumar,Cardiology,Cardiologist,12,15,Available
1,D102,Dr. Priya Sharma,Neurology,Neurologist,8,20,Available
2,D103,Dr. Anil Reddy,Orthopedics,Orthopedic Surgeon,10,15,Busy
3,D104,Dr. Kavitha Rao,Pediatrics,Pediatrician,7,10,Available
4,D105,Dr. Suresh Naik,General Medicine,Physician,15,12,Available

Departments

  department_id   department_name
0         DEP01  General Medicine
1         DEP02        Cardiology
2         DEP03         Neurology
3         DEP04       Orthopedics
4         DEP05        Pediatrics

In [13]:
print("Patients Columns")
print(patients.columns)

print("\nAppointments Columns")
print(appointments.columns)

print("\nHospital ER Columns")
print(er.columns)

print("\nPatient Flow Columns")
print(patient_flow.columns)

print("\nDoctors Columns")
print(doctors.columns)

print("\nDepartments Columns")
print(departments.columns)

Patients Columns
Index(['Patient_ID', 'Age', 'Gender', 'Condition', 'Medication ',
       'Admission_Date', 'Discharge_Date', 'Patient_State',
       'Year_of_Admission', 'Length_of_Stay', 'Readmission', 'Outcome',
       'Satisfaction', 'Insurance_Claimed', 'Total_Cost'],
      dtype='str')

Appointments Columns
Index(['appointment_id', 'patient_id', 'doctor_id', 'appointment_date',
       'appointment_time', 'reason_for_visit', 'status'],
      dtype='str')

Hospital ER Columns
Index(['Patient Id', 'Patient Admission Date', 'Patient First Inital',
       'Patient Last Name', 'Patient Gender', 'Patient Age', 'Patient Race',
       'Department Referral', 'Patient Admission Flag',
       'Patient Satisfaction Score', 'Patient Waittime', 'Patients CM'],
      dtype='str')

Patient Flow Columns
Index(['Patient Id', 'Patient Admission Date', 'Patient Admission Time',
       'Merged', 'Patient Gender', 'Patient Age', 'Patient Race',
       'Department Referral', 'Patient Admission Flag',
       'Patient Satisfaction Score', 'Patient Waittime'],
      dtype='str')

Doctors Columns
Index(['doctor_id', 'doctor_name', 'department', 'specialization',
       'experience_years', 'consultation_time_min', 'availability'],
      dtype='str')

Departments Columns
Index(['department_id', 'department_name'], dtype='str')

In [14]:
print("Patients")
patients.info()

print("\nAppointments")
appointments.info()

print("\nHospital ER")
er.info()

print("\nPatient Flow")
patient_flow.info()

print("\nDoctors")
doctors.info()

print("\nDepartments")
departments.info()

Patients
<class 'pandas.DataFrame'>
RangeIndex: 984 entries, 0 to 983
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Patient_ID         984 non-null    int64
 1   Age                984 non-null    int64
 2   Gender             984 non-null    str
 3   Condition          984 non-null    str
 4   Medication         984 non-null    str
 5   Admission_Date     984 non-null    str
 6   Discharge_Date     984 non-null    str
 7   Patient_State      984 non-null    str
 8   Year_of_Admission  984 non-null    int64
 9   Length_of_Stay     984 non-null    int64
 10  Readmission        984 non-null    str
 11  Outcome            984 non-null    str
 12  Satisfaction       984 non-null    int64
 13  Insurance_Claimed  984 non-null    str
 14  Total_Cost         984 non-null    int64
dtypes: int64(6), str(9)
memory usage: 115.4 KB

Appointments
<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   appointment_id    200 non-null    str
 1   patient_id        200 non-null    str
 2   doctor_id         200 non-null    str
 3   appointment_date  200 non-null    str
 4   appointment_time  200 non-null    str
 5   reason_for_visit  200 non-null    str
 6   status            200 non-null    str
dtypes: str(7)
memory usage: 11.1 KB

Hospital ER
<class 'pandas.DataFrame'>
RangeIndex: 9216 entries, 0 to 9215
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Patient Id                  9216 non-null   str
 1   Patient Admission Date      9216 non-null   str
 2   Patient First Inital        9216 non-null   str
 3   Patient Last Name           9216 non-null   str
 4   Patient Gender              9216 non-null   str
 5   Patient Age                 9216 non-null   int64
 6   Patient Race                9216 non-null   str
 7   Department Referral         3816 non-null   str
 8   Patient Admission Flag      9216 non-null   bool
 9   Patient Satisfaction Score  2517 non-null   float64
 10  Patient Waittime            9216 non-null   int64
 11  Patients CM                 9216 non-null   int64
dtypes: bool(1), float64(1), int64(3), str(7)
memory usage: 801.1 KB

Patient Flow
<class 'pandas.DataFrame'>
RangeIndex: 9216 entries, 0 to 9215
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Patient Id                  9216 non-null   str
 1   Patient Admission Date      9216 non-null   str
 2   Patient Admission Time      9216 non-null   str
 3   Merged                      9216 non-null   str
 4   Patient Gender              9216 non-null   str
 5   Patient Age                 9216 non-null   int64
 6   Patient Race                9216 non-null   str
 7   Department Referral         3816 non-null   str
 8   Patient Admission Flag      9216 non-null   str
 9   Patient Satisfaction Score  2517 non-null   float64
 10  Patient Waittime            9216 non-null   int64
dtypes: float64(1), int64(2), str(8)
memory usage: 792.1 KB

Doctors
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   doctor_id              10 non-null     str
 1   doctor_name            10 non-null     str
 2   department             10 non-null     str
 3   specialization         10 non-null     str
 4   experience_years       10 non-null     int64
 5   consultation_time_min  10 non-null     int64
 6   availability           10 non-null     str
dtypes: int64(2), str(5)
memory usage: 692.0 bytes

Departments
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   department_id    10 non-null     str
 1   department_name  10 non-null     str
dtypes: str(2)
memory usage: 292.0 bytes

In [15]:
print("Patients")
print(patients.isnull().sum())

print("\nAppointments")
print(appointments.isnull().sum())

print("\nHospital ER")
print(er.isnull().sum())

print("\nPatient Flow")
print(patient_flow.isnull().sum())

print("\nDoctors")
print(doctors.isnull().sum())

print("\nDepartments")
print(departments.isnull().sum())

Patients
Patient_ID           0
Age                  0
Gender               0
Condition            0
Medication           0
Admission_Date       0
Discharge_Date       0
Patient_State        0
Year_of_Admission    0
Length_of_Stay       0
Readmission          0
Outcome              0
Satisfaction         0
Insurance_Claimed    0
Total_Cost           0
dtype: int64

Appointments
appointment_id      0
patient_id          0
doctor_id           0
appointment_date    0
appointment_time    0
reason_for_visit    0
status              0
dtype: int64

Hospital ER
Patient Id                       0
Patient Admission Date           0
Patient First Inital             0
Patient Last Name                0
Patient Gender                   0
Patient Age                      0
Patient Race                     0
Department Referral           5400
Patient Admission Flag           0
Patient Satisfaction Score    6699
Patient Waittime                 0
Patients CM                      0
dtype: int64

Patient Flow
Patient Id                       0
Patient Admission Date           0
Patient Admission Time           0
Merged                           0
Patient Gender                   0
Patient Age                      0
Patient Race                     0
Department Referral           5400
Patient Admission Flag           0
Patient Satisfaction Score    6699
Patient Waittime                 0
dtype: int64

Doctors
doctor_id                0
doctor_name              0
department               0
specialization           0
experience_years         0
consultation_time_min    0
availability             0
dtype: int64

Departments
department_id      0
department_name    0
dtype: int64

In [16]:
print("Patients :", patients.duplicated().sum())
print("Appointments :", appointments.duplicated().sum())
print("Hospital ER :", er.duplicated().sum())
print("Patient Flow :", patient_flow.duplicated().sum())
print("Doctors :", doctors.duplicated().sum())
print("Departments :", departments.duplicated().sum())

Patients : 0
Appointments : 0
Hospital ER : 0
Patient Flow : 0
Doctors : 0
Departments : 0

In [17]:
patients.describe(include="all")

,Patient_ID,Age,Gender,Condition,Medication,Admission_Date,Discharge_Date,Patient_State,Year_of_Admission,Length_of_Stay,Readmission,Outcome,Satisfaction,Insurance_Claimed,Total_Cost
count,984.000000,984.000000,984,984,984,984,984,984,984.000000,984.000000,984,984,984.000000,984,984.000000
unique,NaN,NaN,2,15,15,709,723,30,NaN,NaN,2,2,NaN,2,NaN
top,NaN,NaN,Female,Fractured Leg,Cast and Physical Therapy,28-03-2024,20-05-2022,Kerala,NaN,NaN,No,Recovered,NaN,No,NaN
freq,NaN,NaN,524,67,67,4,4,120,NaN,NaN,720,591,NaN,633,NaN
mean,492.500000,53.754065,NaN,NaN,NaN,NaN,NaN,NaN,2023.460366,37.663618,NaN,NaN,3.598577,NaN,8367.479675
std,284.200633,14.941135,NaN,NaN,NaN,NaN,NaN,NaN,1.106926,19.595805,NaN,NaN,0.883002,NaN,7761.990976
min,1.000000,25.000000,NaN,NaN,NaN,NaN,NaN,NaN,2022.000000,1.000000,NaN,NaN,2.000000,NaN,100.000000
25%,246.750000,45.000000,NaN,NaN,NaN,NaN,NaN,NaN,2022.000000,21.000000,NaN,NaN,3.000000,NaN,1000.000000
50%,492.500000,55.000000,NaN,NaN,NaN,NaN,NaN,NaN,2023.000000,38.000000,NaN,NaN,4.000000,NaN,6000.000000
75%,738.250000,65.000000,NaN,NaN,NaN,NaN,NaN,NaN,2024.000000,54.250000,NaN,NaN,4.000000,NaN,15000.000000
max,984.000000,78.000000,NaN,NaN,NaN,NaN,NaN,NaN,2025.000000,76.000000,NaN,NaN,5.000000,NaN,25000.000000